[versions]
cronetOkhttp = "0.1.0"
cronetPlayServices = "18.0.1"

[libraries]
cronet-okhttp = { module = "com.google.net.cronet:cronet-okhttp", version.ref = "cronetOkhttp" }
cronet-playServices = { module = "com.google.android.gms:play-services-cronet", version.ref = "cronetPlayServices" }
timber = "com.jakewharton.timber:timber:5.0.1"