[versions]
core = "1.7.0"
appcompat = "1.4.1"
constraintlayout = "2.0.0"
lifecycle = "2.4.0"
cardView = "1.0.0"
browser = "1.2.0"
dynamicanimation = "1.0.0"
fragment = "1.4.0"
recyclerview = "1.2.1"
swipeRefresh = "1.1.0"
workManager = "2.7.1"
viewpager2 = "1.0.0"
architecture = "2.0.0"
preference = "1.1.1"
testOrchestrator = "1.1.0"
localbroadcastmanager = "1.0.0"
multidex = "2.0.0"
test = "1.4.0"
testRunner = "1.1.0"
testJunit = "1.1.1"
espresso = "3.2.0"
fragmentTesting = "1.1.0-alpha01"
collection = "1.2.0"
navigationktx = "2.3.5"
material = "1.4.0"
activity = "1.6.1"

# Compose
composeActivity = "1.4.0"
composeCommon = "1.3.0"
composeCompiler = "1.3.2"
composeConstraintLayout = "1.0.0"
composeNavigation = "2.4.1"
composeViewmodel = "2.4.1"
accompanist = "0.23.0"
coilCompose = "2.0.0"


[libraries]
plugin-androidx-navigation = {  module = "androidx.navigation:navigation-safe-args-gradle-plugin" , version.ref = "navigationktx" }

androidx-core = {  module = "androidx.core:core-ktx" , version.ref = "core" }
androidx-appcompat = {  module = "androidx.appcompat:appcompat"  , version.ref = "appcompat" }
androidx-constraintlayout = {  module = "androidx.constraintlayout:constraintlayout" , version.ref = "constraintlayout" }

androidx-lifecycle-runtimektx = {  module = "androidx.lifecycle:lifecycle-runtime-ktx" , version.ref = "lifecycle" }
androidx-lifecycle-runtime = {  module = "androidx.lifecycle:lifecycle-runtime" , version.ref = "architecture" }
androidx-lifecycle-livedata = {  module = "androidx.lifecycle:lifecycle-livedata-ktx" , version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = {  module = "androidx.lifecycle:lifecycle-viewmodel-ktx" , version.ref = "lifecycle" }
androidx-lifecycle-extensions = {  module = "androidx.lifecycle:lifecycle-extensions" , version.ref = "architecture" }
androidx-lifecycle-compiler = {  module = "androidx.lifecycle:lifecycle-compiler" , version.ref = "architecture" }

androidx-cardView = {  module = "androidx.cardview:cardview" , version.ref = "cardView" }
androidx-collection = {  module = "androidx.collection:collection" , version.ref = "collection" }
androidx-browser = {  module = "androidx.browser:browser" , version.ref = "browser" }
androidx-dynamicanimation = {  module = "androidx.dynamicanimation:dynamicanimation" , version.ref = "dynamicanimation" }
androidx-fragment = {  module = "androidx.fragment:fragment" , version.ref = "fragment" }
androidx-fragmentktx = {  module = "androidx.fragment:fragment-ktx" , version.ref = "fragment" }
androidx-recyclerview = {  module = "androidx.recyclerview:recyclerview" , version.ref = "recyclerview" }
androidx-swipeRefresh = {  module = "androidx.swiperefreshlayout:swiperefreshlayout" , version.ref = "swipeRefresh" }
androidx-workManager = {  module = "androidx.work:work-runtime-ktx" , version.ref = "workManager" }
androidx-workManager-rxjava = {  module = "androidx.work:work-rxjava2" , version.ref = "workManager" }
androidx-viewpager2 = {  module = "androidx.viewpager2:viewpager2" , version.ref = "viewpager2" }
androidx-preference = {  module = "  androidx.preference:preference" , version.ref = "preference" }
androidx-preferencektx = {  module = "androidx.preference:preference" , version.ref = "preference" }
androidx-testOrchestrator = {  module = "androidx.preference:preference-ktx" , version.ref = "testOrchestrator" }
androidx-localbroadcastmanager = {  module = "androidx.localbroadcastmanager:localbroadcastmanager" , version.ref = "localbroadcastmanager" }
androidx-multidex-instrumentation = {  module = "androidx.multidex:multidex-instrumentation" , version.ref = "multidex" }
androidx-multidex = {  module = "androidx.multidex:multidex" , version.ref = "multidex" }
androidx-paging = { module = "androidx.paging:paging-runtime" , version.ref = "architecture" }
androidx-paging-rxjava = { module = "androidx.paging:paging-rxjava2" , version.ref = "architecture" }
#androidx-test = {  module = "1.3.0" , version.ref = "test" }
androidx-testRunner = {  module = "androidx.test:runner" , version.ref = "testRunner" }
androidx-testJunit = {  module = "androidx.test.ext:junit" , version.ref = "testJunit" }
androidx-espresso-core = {  module = "androidx.test.espresso:espresso-core" , version.ref = "espresso" }
androidx-espresso-contrib = {  module = "androidx.test.espresso:espresso-contrib" , version.ref = "espresso" }
androidx-espresso-intents = {  module = "androidx.test.espresso:espresso-intents" , version.ref = "espresso" }
androidx-fragmentTesting = {  module = "androidx.fragment:fragment-testing" , version.ref = "fragmentTesting" }
androidx-navigation-fragment-ktx = {  module = "androidx.navigation:navigation-fragment-ktx" , version.ref = "navigationktx" }
androidx-navigation-ui = {  module = "androidx.navigation:navigation-ui-ktx" , version.ref = "navigationktx" }
androidx-material = {  module = "com.google.android.material:material" , version.ref = "material" }
androidx-activity = {  module = "androidx.activity:activity-ktx" , version.ref = "activity" }

#androidx-testOrchestrator = {  module = "androidx.test:orchestrator" , version.ref = "fragmentTesting" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui" , version.ref = "composeCommon" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" , version.ref = "composeCommon" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" , version.ref = "composeCommon" }
compose-foundation = { module = "androidx.compose.foundation:foundation" , version.ref = "composeCommon" }
compose-material = { module = "androidx.compose.material:material" , version.ref = "composeCommon" }
compose-icon-core = { module = "androidx.compose.material:material-icons-core" , version.ref = "composeCommon" }
compose-icon-extended = { module = "androidx.compose.material:material-icons-extended" , version.ref = "composeCommon" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata" , version.ref = "composeCommon"}

compose-activity = { module = "androidx.activity:activity-compose" , version.ref = "composeActivity" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" , version.ref = "composeViewmodel" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose" , version.ref = "composeConstraintLayout" }
compose-navigation = { module = "androidx.navigation:navigation-compose" , version.ref = "composeNavigation" }

accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout" , version.ref = "accompanist" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

[bundles]
androidx-lifecycle = ["androidx-lifecycle-runtimektx", "androidx-lifecycle-runtime", "androidx-lifecycle-livedata", "androidx-lifecycle-viewmodel", "androidx-lifecycle-extensions"]
compose-common = ["compose-ui", "compose-tooling", "compose-tooling-preview", "compose-foundation", "compose-material", "compose-icon-core", "compose-icon-extended", "compose-activity", "compose-viewmodel", "compose-constraintlayout", "compose-livedata"]